### ISSUE TITLE
Cargo all commands - ability to specify working directory

### ISSUE THREAD

**Issue by bmc-msft** [spontoreau/rust-azure-devops#6]
My rust project isn't at the root directory of my repo.  As such, the ability to specify the working directory to run cargo is important.

Right now, I use the a powershell script to do each of the cargo commands I need in this fashion:

```
steps:
- powershell: . 'path/to/build-script.ps1' '-build' 'path/to/project' 
  displayName: Build
```

**Comment by spontoreau** [comment]
Hi, you can do that with the "--manifest-path" argument. This argument allows cargo with a specific Cargo.toml file path.

I use this arguments to build projects that aren't at the root directory.

**Comment by spontoreau** [comment]
Without any news for you on this issue, I close it.

For information, I consider that Cargo task needs a version 2 to be more user friendly. If I have time to develop this V2, I will integrate the manifest-path as an option.

**Comment by spontoreau** [comment]
Related to #9

**Comment by spontoreau** [comment]
Done!
